app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/forar
    username: postgres
    password: greSQLdb
    pool-size: 30
spring:
  flyway:
    baseline-on-migrate: true
#  resources:
#    add-mappings: false
#    static-locations: file:/Users/xzack/Downloads/forar/frontend
#  mvc:
#    throw-exception-if-no-handler-found: true
